# Generated by Django 4.0 on 2022-04-18 06:34

from django.db import migrations, models
import django.db.models.deletion
import instapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Datasheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('upload', models.FileField(blank=True, upload_to='Datasheet')),
                ('type', models.CharField(choices=[('gn', 'Generic'), ('sp', 'Specific')], default='sp', max_length=2)),
                ('unit', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Manual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('upload', models.FileField(blank=True, upload_to=instapp.models.re_manual)),
                ('category', models.CharField(choices=[('lv', 'Level'), ('pr', 'Pressure'), ('fl', 'Flow'), ('vb', 'Vibration'), ('cv', 'Control valves'), ('of', 'On-off valves'), ('mv', 'Motorized valves'), ('an', 'Analyzers'), ('fg', 'Fire and Gas'), ('ac', 'Accessory'), ('na', 'Other')], default='lv', max_length=2)),
                ('type', models.CharField(choices=[('tx', 'Transmitter'), ('sw', 'Switch'), ('ga', 'Gauge'), ('na', 'Other')], default='tx', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Pid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=10)),
                ('unit', models.CharField(max_length=2)),
                ('upload', models.FileField(blank=True, upload_to=instapp.models.re_pid)),
            ],
        ),
        migrations.CreateModel(
            name='TwoWire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=30, unique=True)),
                ('unit', models.CharField(default='02', max_length=2)),
                ('upload', models.FileField(blank=True, upload_to=instapp.models.path_2wire)),
            ],
        ),
        migrations.CreateModel(
            name='Inst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.SlugField(max_length=30, verbose_name='Tag Number')),
                ('description', models.TextField(blank=True, max_length=500)),
                ('scaff', models.BooleanField(default=False)),
                ('datasheet', models.ManyToManyField(blank=True, related_name='datasheets', to='instapp.Datasheet')),
                ('manual', models.ManyToManyField(blank=True, related_name='manual', to='instapp.Manual')),
                ('pid', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='instapp.pid')),
                ('wire', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='instapp.twowire')),
            ],
        ),
    ]
