# Generated by Django 4.0 on 2022-04-24 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasheet',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='datasheet',
            name='unit',
            field=models.CharField(choices=[('02', '02'), ('06', '06')], default='02', max_length=2),
        ),
        migrations.AlterField(
            model_name='inst',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='instapp.pid'),
        ),
        migrations.AlterField(
            model_name='pid',
            name='unit',
            field=models.CharField(choices=[('02', '02'), ('06', '06')], default='02', max_length=2),
        ),
        migrations.AlterField(
            model_name='twowire',
            name='unit',
            field=models.CharField(choices=[('02', '02'), ('06', '06')], default='02', max_length=2),
        ),
    ]
