# Generated by Django 4.0 on 2022-05-21 18:24

import datetime
from django.db import migrations, models
import instapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('instapp', '0002_alter_datasheet_name_alter_datasheet_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inst',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 21, 20, 24, 58, 462499)),
        ),
        migrations.AlterField(
            model_name='datasheet',
            name='unit',
            field=models.CharField(choices=[('na', 'No filter'), ('02', '02'), ('06', '06')], default='02', max_length=2),
        ),
        migrations.AlterField(
            model_name='datasheet',
            name='upload',
            field=models.FileField(blank=True, upload_to=instapp.models.datasheet_path),
        ),
        migrations.AlterField(
            model_name='manual',
            name='category',
            field=models.CharField(choices=[('na', 'No filter'), ('lv', 'Level'), ('pr', 'Pressure'), ('fl', 'Flow'), ('tm', 'Temperature'), ('vb', 'Vibration'), ('cv', 'Control valves'), ('of', 'On-off valves'), ('mv', 'Motorized valves'), ('an', 'Analyzers'), ('fg', 'Fire and Gas'), ('na', 'Other')], default='lv', max_length=2),
        ),
        migrations.AlterField(
            model_name='manual',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='manual',
            name='type',
            field=models.CharField(choices=[('na', 'No filter'), ('tx', 'Transmitter'), ('sw', 'Switch'), ('ga', 'Gauge'), ('po', 'Positioner'), ('ct', 'Actuator'), ('bd', 'Body'), ('ac', 'Accessory'), ('na', 'Other')], default='tx', max_length=2),
        ),
        migrations.AlterField(
            model_name='pid',
            name='unit',
            field=models.CharField(choices=[('na', 'No filter'), ('02', '02'), ('06', '06')], default='02', max_length=2),
        ),
        migrations.AlterField(
            model_name='twowire',
            name='unit',
            field=models.CharField(choices=[('na', 'No filter'), ('02', '02'), ('06', '06')], default='02', max_length=2),
        ),
    ]
