# Generated by Django 4.0 on 2022-05-21 18:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('instapp', '0003_inst_date_added_alter_datasheet_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inst',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 21, 18, 33, 29, 583471, tzinfo=utc)),
        ),
    ]
